//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_INSUMOS
    {
        public int id_aplica { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<int> id_insumo { get; set; }
        public Nullable<int> cant_usada { get; set; }
        public Nullable<System.DateTime> fecha_aplic { get; set; }
        public Nullable<int> id_proveedor { get; set; }


        [JsonIgnore]
        public virtual INSUMO INSUMO { get; set; }

        [JsonIgnore]
        public virtual LOTE LOTE { get; set; }

        [JsonIgnore]
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
