//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAFETALDBEntities : DbContext
    {
        public CAFETALDBEntities()
            : base("name=CAFETALDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_INSUMOS> ADM_INSUMOS { get; set; }
        public virtual DbSet<CULTIVO> CULTIVOes { get; set; }
        public virtual DbSet<INSUMO> INSUMOes { get; set; }
        public virtual DbSet<LOTE> LOTEs { get; set; }
        public virtual DbSet<PLANTA> PLANTAs { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<REPORTE> REPORTES { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
