//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAFETALDBEntities : DbContext
    {
        public CAFETALDBEntities()
            : base("name=CAFETALDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_INSUMOS> ADM_INSUMOS { get; set; }
        public virtual DbSet<CULTIVO> CULTIVOes { get; set; }
        public virtual DbSet<INSUMO> INSUMOes { get; set; }
        public virtual DbSet<LOTE> LOTEs { get; set; }
        public virtual DbSet<PLANTA> PLANTAs { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<REPORTE> REPORTES { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
