//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMO()
        {
            this.ADM_INSUMOS = new HashSet<ADM_INSUMOS>();
        }
    
        public int id_insumo { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> f_entrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADM_INSUMOS> ADM_INSUMOS { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
