//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMO()
        {
            this.ADM_INSUMOS = new HashSet<ADM_INSUMOS>();
        }
    
        public int id_insumo { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> f_entrega { get; set; }

        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADM_INSUMOS> ADM_INSUMOS { get; set; }

        [JsonIgnore]
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
