//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTE()
        {
            this.ADM_INSUMOS = new HashSet<ADM_INSUMOS>();
            this.REPORTES = new HashSet<REPORTE>();
            this.PLANTAs = new HashSet<PLANTA>();
        }
    
        public int id_lote { get; set; }
        public int id_usuario { get; set; }
        public string variedad { get; set; }
        public Nullable<System.DateTime> inicio_siembra { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_fin_siembra { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<int> cantidad_plantas { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_cultivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADM_INSUMOS> ADM_INSUMOS { get; set; }
        public virtual CULTIVO CULTIVO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE> REPORTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTA> PLANTAs { get; set; }
    }
}
