//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTA
    {
        public int id_planta { get; set; }
        public int id_lote { get; set; }
        public System.DateTime fecha_plantacion { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
    
        public virtual LOTE LOTE { get; set; }
    }
}
