//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTA
    {
        public int id_planta { get; set; }
        public int id_lote { get; set; }
        public System.DateTime fecha_plantacion { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }

        [JsonIgnore]
        public virtual LOTE LOTE { get; set; }
    }
}
