//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CAFETAL.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public int id_report { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentarios { get; set; }


        [JsonIgnore]
        public virtual LOTE LOTE { get; set; }

        [JsonIgnore]
        public virtual USUARIO USUARIO { get; set; }
    }
}
